#define COMPO_INIT_DECLS \
int SysTimer__Entry(INIT_STRUCT *pInitStruct); \
int SysTime__Entry(INIT_STRUCT *pInitStruct); \
int SysTarget__Entry(INIT_STRUCT *pInitStruct); \
int SysShm__Entry(INIT_STRUCT *pInitStruct); \
int SysOut__Entry(INIT_STRUCT *pInitStruct); \
int SysMem__Entry(INIT_STRUCT *pInitStruct); \
int SysInternalLib__Entry(INIT_STRUCT *pInitStruct); \
int SysInt__Entry(INIT_STRUCT *pInitStruct); \
int SysFlash__Entry(INIT_STRUCT *pInitStruct); \
int SysFileFlash__Entry(INIT_STRUCT *pInitStruct); \
int SysExcept__Entry(INIT_STRUCT *pInitStruct); \
int SysCpuHandling__Entry(INIT_STRUCT *pInitStruct); \
int SysCom__Entry(INIT_STRUCT *pInitStruct); \
int IoDrvUnsafeBridge__Entry(INIT_STRUCT *pInitStruct); \
int CmpSrv__Entry(INIT_STRUCT *pInitStruct); \
int CmpSettingsEmbedded__Entry(INIT_STRUCT *pInitStruct); \
int CmpScheduleTimer__Entry(INIT_STRUCT *pInitStruct); \
int CmpRouterEmbedded__Entry(INIT_STRUCT *pInitStruct);	   \
int CmpNameServiceServer__Entry(INIT_STRUCT *pInitStruct); \
int CmpMonitor2__Entry(INIT_STRUCT *pInitStruct); \
int CmpMemPool__Entry(INIT_STRUCT *pInitStruct); \
int CmpLogEmbedded__Entry(INIT_STRUCT *pInitStruct); \
int CmpIoMgrEmbedded__Entry(INIT_STRUCT *pInitStruct); \
int CmpIoDrvIec__Entry(INIT_STRUCT *pInitStruct); \
int CmpIecTask__Entry(INIT_STRUCT *pInitStruct); \
int CmpEventMgr__Entry(INIT_STRUCT *pInitStruct); \
int CmpDevice__Entry(INIT_STRUCT *pInitStruct); \
int CmpCommunicationLib__Entry(INIT_STRUCT *pInitStruct); \
int CmpChecksum__Entry(INIT_STRUCT *pInitStruct); \
int CmpChannelServerEmbedded__Entry(INIT_STRUCT *pInitStruct); \
int CmpChannelMgrEmbedded__Entry(INIT_STRUCT *pInitStruct); \
int CmpBlkDrvShm__Entry(INIT_STRUCT *pInitStruct); \
int CmpBinTagUtil__Entry(INIT_STRUCT *pInitStruct); \
int CmpAppEmbedded__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAACanL2__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAAMemBlockMan__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAASdoClient__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAATickUtil__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAATick__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAACallback__Entry(INIT_STRUCT *pInitStruct); \
int CmpSocketCanDrv__Entry(INIT_STRUCT *pInitStruct); \
int SysCpuHandling__Entry(INIT_STRUCT *pInitStruct);


#define COMPO_INIT_LIST \
{"SysTimer", SysTimer__Entry, 0}, \
{"SysTime", SysTime__Entry, 0}, \
{"SysTarget", SysTarget__Entry, 0}, \
{"SysShm", SysShm__Entry, 0}, \
{"SysOut", SysOut__Entry, 0}, \
{"SysMem", SysMem__Entry, 0}, \
{"SysInternalLib", SysInternalLib__Entry, 0}, \
{"SysInt", SysInt__Entry, 0}, \
{"SysFlash", SysFlash__Entry, 0}, \
{"SysFileFlash", SysFileFlash__Entry, 0}, \
{"SysExcept", SysExcept__Entry, 0}, \
{"SysCpuHandling", SysCpuHandling__Entry, 0}, \
{"SysCom", SysCom__Entry, 0}, \
{"IoDrvUnsafeBridge", IoDrvUnsafeBridge__Entry, 0}, \
{"CmpSrv", CmpSrv__Entry, 0}, \
{"CmpSettingsEmbedded", CmpSettingsEmbedded__Entry, 0}, \
{"CmpScheduleTimer", CmpScheduleTimer__Entry, 0}, \
{"CmpRouterEmbedded", CmpRouterEmbedded__Entry, 0}, \
{"CmpNameServiceServer", CmpNameServiceServer__Entry, 0}, \
{"CmpMonitor2", CmpMonitor2__Entry, 0}, \
{"CmpMemPool", CmpMemPool__Entry, 0}, \
{"CmpLogEmbedded", CmpLogEmbedded__Entry, 0}, \
{"CmpIoMgrEmbedded", CmpIoMgrEmbedded__Entry, 0}, \
{"CmpIoDrvIec", CmpIoDrvIec__Entry, 0}, \
{"CmpIecTask", CmpIecTask__Entry, 0}, \
{"CmpEventMgr", CmpEventMgr__Entry, 0}, \
{"CmpDevice", CmpDevice__Entry, 0}, \
{"CmpCommunicationLib", CmpCommunicationLib__Entry, 0}, \
{"CmpChecksum", CmpChecksum__Entry, 0}, \
{"CmpChannelServerEmbedded", CmpChannelServerEmbedded__Entry, 0}, \
{"CmpChannelMgrEmbedded", CmpChannelMgrEmbedded__Entry, 0}, \
{"CmpBlkDrvShm", CmpBlkDrvShm__Entry, 0}, \
{"CmpBinTagUtil", CmpBinTagUtil__Entry, 0}, \
{"CmpAppEmbedded", CmpAppEmbedded__Entry, 0}, \
{"CmpCAACanL2", CmpCAACanL2__Entry, 0}, \
{"CmpCAAMemBlockMan", CmpCAAMemBlockMan__Entry, 0}, \
{"CmpCAASdoClient", CmpCAASdoClient__Entry, 0}, \
{"CmpCAATickUtil", CmpCAATickUtil__Entry, 0}, \
{"CmpCAATick", CmpCAATick__Entry, 0}, \
{"CmpCAACallback", CmpCAACallback__Entry, 0}, \
{"CmpSocketCanDrv", CmpSocketCanDrv__Entry, 0}, \
{"SysCpuHandling", SysCpuHandling__Entry, 0}, \
{"", NULL, 0}

