/**
 * !!! THIS FILE IS AUTOGENERATED !!!
 *
 * This file will be overwritten with the target definitions
 * of the customer upon delivery. So, don't modify this file
 * directly!
 */

#ifndef __TARGETDEFINES_H_
#define __TARGETDEFINES_H_
#endif
