SysTarget.o : ..\..\components\systarget\systarget.c
SysTargetWin32.o : ..\..\platforms\windows\sys\systargetwin32.c
CmpCommunicationLib.o : ..\..\components\cmpcommunicationlib\cmpcommunicationlib.c
CmpLogEmbedded.o : ..\..\components\cmplogembedded\cmplogembedded.c
CmpLogEmbeddedSrv.o : ..\..\components\cmplogembedded\cmplogembeddedsrv.c
CmpChecksum.o : ..\..\components\cmpchecksum\cmpchecksum.c
CmpChecksumCrc16.o : ..\..\components\cmpchecksum\cmpchecksumcrc16.c
CmpChecksumCrc32.o : ..\..\components\cmpchecksum\cmpchecksumcrc32.c
CmpNameServiceServer.o : ..\..\components\cmpnameserviceserver\cmpnameserviceserver.c
CmpBlkDrvCom.o : ..\..\components\cmpblkdrvcom\cmpblkdrvcom.c
SysCom.o : ..\..\components\syscom\syscom.c
SysComWin32.o : ..\..\platforms\windows\sys\syscomwin32.c
CmpIoDrvIec.o : ..\..\components\cmpiodrviec\cmpiodrviec.c
CmpAppEmbedded.o : ..\..\components\cmpappembedded\cmpappembedded.c
CmpAppEmbeddedSrv.o : ..\..\components\cmpappembedded\cmpappembeddedsrv.c
CmpIecTask.o : ..\..\components\cmpiectask\cmpiectask.c
CmpChannelMgrEmbedded.o : ..\..\components\cmpchannelmgrembedded\cmpchannelmgrembedded.c
CmpEventMgr.o : ..\..\components\cmpeventmgr\cmpeventmgr.c
CmpDevice.o : ..\..\components\cmpdevice\cmpdevice.c
CmpDeviceSrv.o : ..\..\components\cmpdevice\cmpdevicesrv.c
SysFlash.o : ..\..\components\sysflash\sysflash.c
SysFlashWin32.o : ..\..\platforms\windows\sys\sysflashwin32.c
CmpChannelServerEmbedded.o : ..\..\components\cmpchannelserverembedded\cmpchannelserverembedded.c
SysMem.o : ..\..\components\sysmem\sysmem.c
SysMemWin32.o : ..\..\platforms\windows\sys\sysmemwin32.c
CmpMemPool.o : ..\..\components\cmpmempool\cmpmempool.c
CmpIoMgrEmbedded.o : ..\..\components\cmpiomgrembedded\cmpiomgrembedded.c
CmpSrv.o : ..\..\components\cmpsrv\cmpsrv.c
SysCpuHandling.o : ..\..\components\syscpuhandling\syscpuhandling.c
SysCpuHandlingWin32.o : ..\..\platforms\windows\sys\syscpuhandlingwin32.c
SysExcept.o : ..\..\components\sysexcept\sysexcept.c
SysExceptWin32.o : ..\..\platforms\windows\sys\sysexceptwin32.c
CM.o : ..\..\components\componentmanager\cm.c
CMBasicChecks.o : ..\..\components\componentmanager\cmbasicchecks.c
CMUtils.o : ..\..\components\componentmanager\cmutils.c
MainWin32.o : ..\..\platforms\windows\mainwin32.c
SysOut.o : ..\..\components\sysout\sysout.c
SysOutWin32.o : ..\..\platforms\windows\sys\sysoutwin32.c
SysTime.o : ..\..\components\systime\systime.c
SysTimeWin32.o : ..\..\platforms\windows\sys\systimewin32.c
SysInternalLibDefault.o : ..\..\components\sysinternallib\sysinternallibdefault.c
CmpSettingsEmbedded.o : ..\..\components\cmpsettingsembedded\cmpsettingsembedded.c
CmpSettingsEmbeddedSrv.o : ..\..\components\cmpsettingsembedded\cmpsettingsembeddedsrv.c
CmpScheduleEmbedded.o : ..\..\components\cmpscheduleembedded\cmpscheduleembedded.c
CmpRouterEmbedded.o : ..\..\components\cmprouterembedded\cmprouterembedded.c
CmpRouterEmbeddedAddrSrvc.o : ..\..\components\cmprouterembedded\cmprouterembeddedaddrsrvc.c
CmpBlkDrvUdp.o : ..\..\components\cmpblkdrvudp\cmpblkdrvudp.c
CmpMonitor.o : ..\..\components\cmpmonitor\cmpmonitor.c
SysFileFlash.o : ..\..\components\sysfileflash\sysfileflash.c
SysSocket.o : ..\..\components\syssocket\syssocket.c
SysSocketWin32.o : ..\..\platforms\windows\sys\syssocketwin32.c
CmpBinTagUtil.o : ..\..\components\cmpbintagutil\cmpbintagutil.c
