/**
                            * <interfacename>CoDeSysControl_Compact_CAN_NOTIMPL_H</interfacename>
                            * <description>
                            * <p> Defines all optional interfaces to '_NOTIMPLEMENTED', if no component is active implementing this interface.</p>
                            * </description>
                            *
                            * <copyright>(c) 2003-2008 3S-Smart Software Solutions</copyright>
                            */


#ifndef _CODESYSCONTROL_COMPACT_CAN_NOTIMPL_H_
#define _CODESYSCONTROL_COMPACT_CAN_NOTIMPL_H_



#define CMPAPPFORCE_NOTIMPLEMENTED
#define CMPASYNCMGR_NOTIMPLEMENTED
#define CMPCAACALLBACK_NOTIMPLEMENTED
#define CMPCRYPTMD5_NOTIMPLEMENTED
#define CMPCRYPTO_NOTIMPLEMENTED
#define CMPEDGEGATEWAY_NOTIMPLEMENTED
#define CMPMEMGC_NOTIMPLEMENTED
#define CMPMONITOR2_NOTIMPLEMENTED
#define CMPNAMESERVICECLIENT_NOTIMPLEMENTED
#define CMPSIL2_NOTIMPLEMENTED
#define CMPSECURECHANNEL_NOTIMPLEMENTED
#define CMPSECURITYMANAGER_NOTIMPLEMENTED
#define CMPSESSIONINFORMATION_NOTIMPLEMENTED
#define CMPSUPERVISOR_NOTIMPLEMENTED
#define CMPTRACEMGR_NOTIMPLEMENTED
#define CMPUSERMGR_NOTIMPLEMENTED
#define SYSCPUBREAKPOINTS_NOTIMPLEMENTED
#define SYSCPUMULTICORE_NOTIMPLEMENTED
#define SYSEVENT_NOTIMPLEMENTED
#define SYSINT_NOTIMPLEMENTED
#define SYSPROCESS_NOTIMPLEMENTED
#define SYSREADWRITELOCK_NOTIMPLEMENTED
#define SYSSEM_NOTIMPLEMENTED
#define SYSSHM_NOTIMPLEMENTED
#define SYSTASK_NOTIMPLEMENTED
#define SYSTIMERTC_NOTIMPLEMENTED
#define SYSTIMER_NOTIMPLEMENTED


#endif  /* _CODESYSCONTROL_COMPACT_CAN_NOTIMPL_H_*/
