/**
 * <interfacename>CoDeSysControl_Compact_NOTIMPL_H</interfacename>
 * <description>
 * <p> Defines all optional interfaces to '_NOTIMPLEMENTED', if no component is active implementing this interface.</p>
 * </description>
 *
 * <copyright>(c) 2003-2008 3S-Smart Software Solutions</copyright>
 */


#ifndef _CODESYSCONTROL_COMPACT_NOTIMPL_H_
#define _CODESYSCONTROL_COMPACT_NOTIMPL_H_


#define CMPAPPBP_NOTIMPLEMENTED
#define CMPEVENTMGR_NOTIMPLEMENTED
#define CMPNAMESERVICECLIENT_NOTIMPLEMENTED
 /* #define CMPAPPFORCE_NOTIMPLEMENTED */
#define CMPASYNCMGR_NOTIMPLEMENTED
#define CMPIODRVDPV1C1MASTER_NOTIMPLEMENTED
#define CMPIODRVDPV1C2MASTER_NOTIMPLEMENTED
/* #define CMPIODRVIEC_NOTIMPLEMENTED */
#define CMPMONITOR_NOTIMPLEMENTED
/* #define CMPIODRV_NOTIMPLEMENTED */
#define CMPIODRVPARAMETER2_NOTIMPLEMENTED
#define CMPIODRVPARAMETER_NOTIMPLEMENTED
#define CMPIODRVPROFINET_NOTIMPLEMENTED
#define CMPLOGBACKEND_NOTIMPLEMENTED
/* #define CMPLOG_NOTIMPLEMENTED */
/* #define CMPLOGSRV_NOTIMPLEMENTED */
#define CMPSIL2_NOTIMPLEMENTED
#define CMPTRACEMGR_NOTIMPLEMENTED
#define CMPMEMGC_NOTIMPLEMENTED
#define CMPUSERMGR_NOTIMPLEMENTED

#define SYSOUT_NOTIMPLEMENTED
#define SYSINT_NOTIMPLEMENTED
#define SYSSEM_NOTIMPLEMENTED
#define SYSSHM_NOTIMPLEMENTED
#define SYSTASK_NOTIMPLEMENTED
#define SYSTIMER_NOTIMPLEMENTED
#define SYSTIMERTC_NOTIMPLEMENTED

#define CMPMONITOR2_NOTIMPLEMENTED

#define CMPCODEMETER_NOTIMPLEMENTED

#endif  /* _CODESYSCONTROL_COMPACT_NOTIMPL_H_*/
