CDS3_DECLARE_COMPONENTS_LIST_BEGIN(uRtsWin)
	CDS3_ADD_COMPONENT_ENTRY(SysInt)
	CDS3_ADD_COMPONENT_ENTRY(SysMem)
	CDS3_ADD_COMPONENT_ENTRY(SysTime)
	CDS3_ADD_COMPONENT_ENTRY(SysTarget)
	CDS3_ADD_COMPONENT_ENTRY(SysCpuHandling)
	CDS3_ADD_COMPONENT_ENTRY(SysSocket)
	CDS3_ADD_COMPONENT_ENTRY(SysCom)
	CDS3_ADD_COMPONENT_ENTRY(SysFlash)
	CDS3_ADD_COMPONENT_ENTRY(SysFileFlash)
	CDS3_ADD_COMPONENT_ENTRY(SysExcept)
	CDS3_ADD_COMPONENT_ENTRY(SysInternalLib)
	CDS3_ADD_COMPONENT_ENTRY(CmpMemPool)
	CDS3_ADD_COMPONENT_ENTRY(CmpHeapPool)
	CDS3_ADD_COMPONENT_ENTRY(CmpAppEmbedded)
	CDS3_ADD_COMPONENT_ENTRY(CmpAppForce)
	CDS3_ADD_COMPONENT_ENTRY(CmpBinTagUtil)
	CDS3_ADD_COMPONENT_ENTRY(CmpBlkDrvUdp)
	CDS3_ADD_COMPONENT_ENTRY(CmpBlkDrvCom)
	CDS3_ADD_COMPONENT_ENTRY(CmpChannelMgrEmbedded)
	CDS3_ADD_COMPONENT_ENTRY(CmpChannelServerEmbedded)
	CDS3_ADD_COMPONENT_ENTRY(CmpChecksum)
	CDS3_ADD_COMPONENT_ENTRY(CmpCommunicationLib)
	CDS3_ADD_COMPONENT_ENTRY(CmpDevice)
	CDS3_ADD_COMPONENT_ENTRY(CmpIecTask)
	CDS3_ADD_COMPONENT_ENTRY(CmpIoMgrEmbedded)
	CDS3_ADD_COMPONENT_ENTRY(CmpIoDrvIec)
	/*CDS3_ADD_COMPONENT_ENTRY(CmpMonitor2)*/
	CDS3_ADD_COMPONENT_ENTRY(CmpMonitor)
	CDS3_ADD_COMPONENT_ENTRY(CmpNameServiceServer)
	CDS3_ADD_COMPONENT_ENTRY(CmpLogEmbedded)
	CDS3_ADD_COMPONENT_ENTRY(CmpRouterEmbedded)
	CDS3_ADD_COMPONENT_ENTRY(CmpRetain)
	CDS3_ADD_COMPONENT_ENTRY(CmpScheduleEmbedded)
	CDS3_ADD_COMPONENT_ENTRY(CmpSettingsEmbedded)
	CDS3_ADD_COMPONENT_ENTRY(CmpSrv)
	CDS3_ADD_COMPONENT_ENTRY(IoDrvTemplate)
CDS3_DECLARE_COMPONENTS_LIST_END(uRtsWin)

/*int SysOut__Entry(INIT_STRUCT *pInitStruct); */
/*int SysCom__Entry(INIT_STRUCT *pInitStruct); */
/*int CmpLogEmbedded__Entry(INIT_STRUCT *pInitStruct); */
/*int CmpEventMgr__Entry(INIT_STRUCT *pInitStruct); */
/*int CmpBlkDrvCom__Entry(INIT_STRUCT *pInitStruct); */


