/**
 * !!! THIS FILE IS AUTOGENERATED !!!
 *
 * This file will be overwritten with the target definitions
 * of the customer upon delivery. So, don't modify this file
 * directly!
 */

#ifndef __TARGETDEFINES_H_
#define __TARGETDEFINES_H_

#define SYSTARGET_SIGNATUREID 0xB2D2E51B
#define SYSTARGET_DEVICE_TYPE SYSTARGET_TYPE_COMMUNICATION
#define SYSTARGET_VENDOR_ID   0x0000
#define SYSTARGET_DEVICE_ID   0x0001
#define SYSTARGET_DEVICE_MASK 0x0000
#define SYSTARGET_VENDOR_NAME "3S - Smart Software Solutions GmbH"
#define SYSTARGET_DEVICE_NAME "CODESYS Control - Device Management Service"

#endif
