/**
 * !!! THIS FILE IS AUTOGENERATED !!!
 *
 * This file will be overwritten with the target definitions
 * of the customer upon delivery. So, don't modify this file
 * directly!
 */

#ifndef __TARGETDEFINES_H_
#define __TARGETDEFINES_H_

#define SYSTARGET_SIGNATUREID		0x35B4453A
#define SYSTARGET_DEVICE_TYPE		SYSTARGET_TYPE_PROGRAMMABLE
#define SYSTARGET_VENDOR_ID			RTS_VENDORID_3S
#define SYSTARGET_DEVICE_ID			0x8024
#define SYSTARGET_DEVICE_MASK		0x0000
#define SYSTARGET_VENDOR_NAME		"3S-Smart Software Solutions GmbH"
#define SYSTARGET_DEVICE_NAME		"MicroRuntime"
#define SYSTARGET_DEVICE_VERSION	RTS_VERSION

#endif
