/**
 * !!! THIS FILE IS AUTOGENERATED !!!
 *
 * This file will be overwritten with the target definitions
 * of the customer upon delivery. So, don't modify this file
 * directly!
 */

#ifndef __TARGETDEFINES_H_
#define __TARGETDEFINES_H_

#ifndef SYSTARGET_SIGNATUREID
	#define SYSTARGET_SIGNATUREID 0x905400BC
#endif

#ifndef SYSTARGET_DEVICE_TYPE
	#define SYSTARGET_DEVICE_TYPE 4102
#endif

#ifndef SYSTARGET_VENDOR_ID
	#define SYSTARGET_VENDOR_ID   0x10a4
#endif

#ifndef SYSTARGET_DEVICE_ID
	#define SYSTARGET_DEVICE_ID   0x0062
#endif

#ifndef SYSTARGET_DEVICE_MASK
	#define SYSTARGET_DEVICE_MASK 0x0000
#endif

#ifndef SYSTARGET_VENDOR_NAME
	#define SYSTARGET_VENDOR_NAME "Kendrion Kuhnke Automation"
#endif

#ifndef SYSTARGET_DEVICE_NAME
	#define SYSTARGET_DEVICE_NAME "ECONO 206-Multicore"
#endif

#ifndef SYSTARGET_DEVICE_VERSION
	#define SYSTARGET_DEVICE_VERSION 0x03050e28
#endif

/*#ifndef TRG_ARM
	#define TRG_ARM
#endif*/

#endif /* __TARGETDEFINES_H_ */
